=== xteamdimension/continuum-arema/Continuum/Continuum/Levels/LevelSchema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <!-- Definizione dei tipi e dei gruppi di attributi -->
  <xs:simpleType name="weaponType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Gun" />
      <xs:enumeration value="RocketLauncher" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="powerupType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Gun" />
      <xs:enumeration value="Rocket" />
      <xs:enumeration value="PlasmaGranade" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="probability">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:attributeGroup name="defaultAttributes">
    <xs:attribute name="timestamp" type="xs:float" use="required" />
    <xs:attribute name="texture" type="xs:string" use="required" />
  </xs:attributeGroup>
  
  <xs:attributeGroup name="randomizerAttributes">
    <xs:attributeGroup ref="defaultAttributes" />
    <xs:attribute name="launchProbabilityPerSecond" type="probability" use="required" />
    <xs:attribute name="probabilityIncrementPerMinute" type="probability" use="optional" />
    <xs:attribute name="pobabilityMax" type="probability" use="optional" />
  </xs:attributeGroup>
  <!-- Fine definizione dei tipi di attributi -->
  
  <!-- level -->
  <xs:element name="level">
    <xs:complexType>
      
      <!-- Tutti i tag contenuti in level-->
      <xs:sequence>

        <!-- texturesDeclaration (contiene la dichiarazione di tutte le textures richiamate in startlevel)-->
        <xs:element name="texturesDeclaration" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">

              <!-- texture -->
              <xs:element name="texture" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="id" type="xs:string" use="required" />
                  <xs:attribute name="path" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:choice>
            
          </xs:complexType>
        </xs:element>
        
        <!-- randomVariablesDeclaration (contiene la dichiarazione di tutte le variabili aleatorie richiamate in startlevel)-->
        <xs:element name="randomVariablesDeclaration" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              
              <!-- randomVariable -->
              <xs:element name="randomVariable" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="id" type="xs:string" use="required" />
                  <xs:attribute name="mean" type="xs:float" use="required" />
                  <xs:attribute name="standardDeviation" type="xs:float" use="required" />
                  <xs:attribute name="meanIncrementPerMinute" type="xs:float" use="optional" />
                  <xs:attribute name="maxValue" type="xs:float" use="optional" />
                  <xs:attribute name="minValue" type="xs:float" use="optional" />
                </xs:complexType>
              </xs:element>
              
              <!-- timeDependentVar -->
              <xs:element name="timeDependentVar" minOccurs="0" maxOccurs="unbounded" >
                <xs:complexType>
                  <xs:attribute name="id" type="xs:string" use="required" />
                  <xs:attribute name="initialValue" type="xs:float" use="required" />
                  <xs:attribute name="valueIncrementPerMinute" type="xs:float" use="optional" />
                  <xs:attribute name="valueDecrementPerMinute" type="xs:float" use="optional" />
                  <xs:attribute name="maxValue" type="xs:float" use="optional" />
                  <xs:attribute name="minValue" type="xs:float" use="optional" />
                </xs:complexType>
              </xs:element>
              
            </xs:choice>
          </xs:complexType>
        </xs:element>
        
        <!-- startlevel (contiene tutti i tag che generano elementi a runtime)-->
        <xs:element name="startlevel" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <!-- ###############################################################
              Definire qua tutti i nuovi tipi elementi consentiti dopo startlevel
              ####################################################################-->

              <!-- backgroundTexture-->
              <xs:element name="backgroundTexture" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attributeGroup ref="defaultAttributes" />
                  <xs:attribute name="level" type="xs:nonNegativeInteger" use="required" />
                  <xs:attribute name="speed" type="xs:float" use="required" />
                  <xs:attribute name="transitionTexture" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>

              <!-- TachyonStream-->
              <xs:element name="tachyonStream" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attributeGroup ref="defaultAttributes" />
                  <xs:attribute name="duration" type="xs:float" use="required" />
                  <xs:attribute name="xposition" type="xs:integer" use="required" />
                </xs:complexType>
              </xs:element>
              
              <!-- asteroid -->
              <xs:element name="asteroid" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attributeGroup ref="defaultAttributes" />
                  <xs:attribute name="xposition" type="xs:integer" use="required" />
                  <xs:attribute name="speed" type="xs:float" use="required" />
                  <xs:attribute name="life" type="xs:nonNegativeInteger" use="required" />
                </xs:complexType>
              </xs:element>
              
              <!-- animation -->
              <xs:element name="animation" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attributeGroup ref="defaultAttributes" />
                  <xs:attribute name="x" type="xs:integer" use="required" />
                  <xs:attribute name="y" type="xs:integer" use="required" />
                  <xs:attribute name="frames" type="xs:nonNegativeInteger" use="required" />
                  <xs:attribute name="rows" type="xs:nonNegativeInteger" use="required" />
                  <xs:attribute name="cols" type="xs:nonNegativeInteger" use="required" />
                  <xs:attribute name="fps" type="xs:nonNegativeInteger" use="required" />
                  <xs:attribute name="rotation" type="xs:float" use="required" />
                  <xs:attribute name="rotationspeed" type="xs:float" use="required" />
                </xs:complexType>
              </xs:element>

              <!-- enemy -->
              <xs:element name="enemy" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attributeGroup ref="defaultAttributes" />
                  <xs:attribute name="x" type="xs:integer" use="required" />
                  <xs:attribute name="y" type="xs:integer" use="required" />
                  <xs:attribute name="speed" type="xs:float" use="required" />
                  <xs:attribute name="weapon" type="weaponType" use="required" />
                  <xs:attribute name="life" type="xs:nonNegativeInteger" use="required" />
                  <xs:attribute name="powerup" type="powerupType" use="optional" />
                </xs:complexType>
              </xs:element>
              
              <!-- enemyRandomizer -->
              <xs:element name="enemyRandomizer" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attributeGroup ref="randomizerAttributes" />
                  <xs:attribute name="weapon" type="weaponType" use="required" />
                  <xs:attribute name="powerUpProbabilityPerLaunch" type="probability" use="optional" />
                  <xs:attribute name="rocketPowerUpProbability" type="probability" use="optional" />
                  <xs:attribute name="granadePowerUpProbability" type="probability" use="optional" />
                  <xs:attribute name="speedRandomVariable" type="xs:string" use="required" />
                  <xs:attribute name="lifeRandomVariable" type="xs:string" use="required" />
                  <xs:attribute name="maxSimultaneousEnemies" type="xs:string" use="optional" />
                  <xs:attribute name="maxSecondsWithoutEnemies" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
              
              <!-- asteroidRandomizer -->
              <xs:element name="asteroidRandomizer" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attributeGroup ref="randomizerAttributes" />
                  <xs:attribute name="speedRandomVariable" type="xs:string" use="required" />
                  <xs:attribute name="lifeRandomVariable" type="xs:string" use="required" />
                  <xs:attribute name="maxSimultaneousAsteroids" type="xs:string" use="optional" />
                  <xs:attribute name="maxSecondsWithoutAsteroids" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>

              <!-- tachyonStreamRandomizer -->
              <xs:element name="tachyonStreamRandomizer" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attributeGroup ref="randomizerAttributes" />
                  <xs:attribute name="durationRandomVariable" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
              
            </xs:choice>
          </xs:complexType>
        </xs:element>
        <!--Fine di startlevel-->
        
        <xs:element name="endlevel" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
      <!-- Fine dei tag contenuti in level-->
      
      <!-- Attributi di level -->
      <xs:attribute name="title" type="xs:string" use="required" />
      <xs:attribute name="subtitle" type="xs:string" use="required" />
      <xs:attribute name="duration" type="xs:nonNegativeInteger" use="required" />
      <xs:attribute name="numlevels" type="xs:nonNegativeInteger" use="required" />
    </xs:complexType>
  </xs:element>
  <!-- Fine di level-->
  
</xs:schema>

=== xteamdimension/continuum-arema/Continuum/Continuum/Levels/Level1.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LevelSchema.xsd" 
       title="CONTINUUM" subtitle="finira prima o poi..." duration="200" numlevels="1">
  <texturesDeclaration>
    <texture id="playership" path="Ships/ship" />
    <texture id="roccia" path="Backgrounds/background_roccia"/>
    <texture id="gunbullet" path="Weapons/gunBullet"/>
    <texture id="enemybullet" path="Weapons/enemyBullet"/>
    <texture id="shadow" path="Effects/shadowcorner"/>
    <texture id="asteroid" path="Asteroids/asteroid"/>
    <texture id="damagesmoke" path="Animations/animation" />
    <texture id="explosion" path="Animations/explosion"/>
    <texture id="enemyeasy" path="Enemies/easy" />
    <texture id="enemynormal" path="Enemies/normal"/>
    <texture id="tachyonstream" path="Animations/TachyonStream"/>
    <texture id="tachyon" path="Effects/tachyon"/>
    <texture id="rocket" path="Weapons/rocket"/>
    <texture id="followingrocket" path="Weapons/rocketfollower"/>
    <texture id="gunpowerup" path="PowerUps/gunPowerUp"/>
    <texture id="rocketpowerup" path="PowerUps/rocketPowerUp"/>
    <texture id="void" path="Effects/void" />
    <texture id="plasmagranade" path="Weapons/plasmagranade"/>
    <texture id="scope" path="Weapons/scope"/>
  </texturesDeclaration>
  
  <startlevel>
    <backgroundTexture timestamp="0" texture="roccia" level="0" speed="300"/>
    <asteroid timestamp="5" life="50" xposition="0" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="10" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="20" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="30" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="40" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="50" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="60" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="70" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="80" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="90" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="100" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="110" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="120" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="130" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="140" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="150" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="160" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="170" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="180" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="190" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="200" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="210" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="220" speed="500" texture="asteroid" />
    <asteroid timestamp="5" life="50" xposition="230" speed="500" texture="asteroid" />
    <enemy timestamp="12" x="300" y="-10" speed="0.1" texture="enemyeasy" weapon="Gun" life="3" powerup="Gun"/>
    <enemy timestamp="20" x="100" y="-10" speed="0.1" texture="enemyeasy" weapon="Gun" life="5" powerup="Rocket"/>
    <enemy timestamp="32" x="300" y="-10" speed="0.1" texture="enemyeasy" weapon="Gun" life="6" powerup="Gun"/>
    <tachyonStream timestamp="40" duration="5" xposition="150" texture="tachyonstream"/>
    <enemy timestamp="50" x="200" y="-10" speed="0.1" texture="enemyeasy" weapon="Gun" life="10" powerup="Gun"/>
    <asteroid timestamp="55" life="20" speed="300" texture="asteroid" xposition="100" />
    <asteroid timestamp="55" life="50" speed="500" texture="asteroid" xposition="300" />
    <asteroid timestamp="56" life="30" speed="400" texture="asteroid" xposition="200" />
    <asteroid timestamp="57" life="40" speed="1000" texture="asteroid" xposition="150" />
    <tachyonStream timestamp="65" duration="5" xposition="300" texture="tachyonstream"/>
    <enemy timestamp="70" x="300" y="-10" speed="0.1" texture="enemyeasy" weapon="Gun" life="5" powerup="Gun"/>
    <enemy timestamp="76" x="100" y="-10" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="3" powerup="Rocket"/>
    <enemy timestamp="85" x="200" y="-10" speed="0.1" texture="enemynormal" weapon="Gun" life="4" powerup="Gun"/>
    <asteroid timestamp="95" life="20" xposition="300" speed="120" texture="asteroid" />
    <asteroid timestamp="98" life="30" xposition="600" speed="200" texture="asteroid" />
    <asteroid timestamp="99" life="10" xposition="400" speed="180" texture="asteroid" />
    <asteroid timestamp="100" life="40" xposition="700" speed="250" texture="asteroid" />
    <tachyonStream timestamp="100" duration="5" xposition="350" texture="tachyonstream"/>
    <enemy timestamp="110" x="300" y="-10" speed="0.1" texture="enemyeasy" weapon="Gun" life="5" powerup="Gun"/>
    <enemy timestamp="110" x="-10" y="200" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="3" powerup="Rocket"/>
    <enemy timestamp="110" x="200" y="-10" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="5" powerup="Rocket"/>
    <enemy timestamp="110" x="300" y="-10" speed="0.1" texture="enemyeasy" weapon="Gun" life="5" powerup="Gun"/>
    <enemy timestamp="110" x="410" y="200" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="6" powerup="Rocket"/>
    <enemy timestamp="110" x="200" y="-10" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="7" powerup="Rocket"/>
    <enemy timestamp="130" x="300" y="-10" speed="0.1" texture="enemyeasy" weapon="Gun" life="5" powerup="Gun"/>
    <enemy timestamp="130" x="-10" y="200" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="8" powerup="Rocket"/>
    <enemy timestamp="130" x="200" y="-10" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="9" powerup="Rocket"/>
    <enemy timestamp="130" x="300" y="-10" speed="0.1" texture="enemyeasy" weapon="Gun" life="5" powerup="Gun"/>
    <enemy timestamp="130" x="410" y="200" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="10" powerup="Rocket"/>
    <enemy timestamp="130" x="200" y="-10" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="11" powerup="Gun"/>
    <tachyonStream timestamp="135" duration="5" xposition="100" texture="tachyonstream"/>
    <enemy timestamp="140" x="300" y="-10" speed="0.1" texture="enemyeasy" weapon="Gun" life="5" powerup="Gun"/>
    <enemy timestamp="140" x="-10" y="200" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="12" powerup="Rocket"/>
    <enemy timestamp="140" x="200" y="-10" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="13" powerup="Rocket"/>
    <enemy timestamp="140" x="300" y="-10" speed="0.1" texture="enemyeasy" weapon="Gun" life="5" powerup="Gun"/>
    <enemy timestamp="140" x="410" y="200" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="14" powerup="Rocket"/>
    <enemy timestamp="140" x="200" y="-10" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="15" powerup="Rocket"/>
    <enemy timestamp="140" x="300" y="-10" speed="0.1" texture="enemyeasy" weapon="Gun" life="5" powerup="Gun"/>
    <enemy timestamp="140" x="-10" y="200" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="16" powerup="Rocket"/>
    <enemy timestamp="140" x="200" y="-10" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="20" powerup="Rocket"/>
    <enemy timestamp="140" x="300" y="-10" speed="0.1" texture="enemyeasy" weapon="Gun" life="5" powerup="Gun"/>
    <enemy timestamp="140" x="410" y="200" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="25" powerup="Rocket"/>
    <enemy timestamp="140" x="200" y="-10" speed="0.1" texture="enemynormal" weapon="RocketLauncher" life="30" powerup="Gun"/>
    <asteroid timestamp="160" life="20" xposition="300" speed="120" texture="asteroid" />
    <asteroid timestamp="160" life="30" xposition="600" speed="200" texture="asteroid" />
    <asteroid timestamp="160" life="10" xposition="400" speed="180" texture="asteroid" />
    <asteroid timestamp="160" life="40" xposition="700" speed="250" texture="asteroid" />
  </startlevel>
  <endlevel />
</level>

=== xteamdimension/continuum-arema/Continuum/Continuum/Levels/RandomLevel.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LevelSchema.xsd" 
       title="CONTINUUM" subtitle="finira prima o poi..." duration="0" numlevels="2">

  <texturesDeclaration>
    <texture id="playership" path="Ships/ship" />
    <texture id="stars" path="Backgrounds/stars"/>
    <texture id="gunbullet" path="Weapons/gunBullet"/>
    <texture id="enemybullet" path="Weapons/enemyBullet"/>
    <texture id="shadow" path="Effects/shadowcorner"/>
    <texture id="asteroid" path="Asteroids/asteroid"/>
    <texture id="explosionChip1" path="Effects/explosionChip1"/>
    <texture id="explosionChip2" path="Effects/explosionChip2"/>
    <texture id="explosionChip3" path="Effects/explosionChip3"/>
    <texture id="granadeChip1" path="Effects/granadeChip1"/>
    <texture id="granadeChip2" path="Effects/granadeChip2"/>
    <texture id="granadeChip3" path="Effects/granadeChip3"/>
    <texture id="asteroidChip1" path="Effects/asteroidChip1"/>
    <texture id="asteroidChip2" path="Effects/asteroidChip2"/>
    <texture id="asteroidChip3" path="Effects/asteroidChip3"/>
    <texture id="enemyeasy" path="Enemies/easy" />
    <texture id="enemynormal" path="Enemies/normal"/>
    <texture id="tachyonstream" path="Animations/TachyonStream"/>
    <texture id="tachyon" path="Effects/tachyon"/>
    <texture id="rocket" path="Weapons/rocket"/>
    <texture id="followingrocket" path="Weapons/rocketfollower"/>
    <texture id="gunpowerup" path="PowerUps/gunPowerUp"/>
    <texture id="rocketpowerup" path="PowerUps/rocketPowerUp"/>
    <texture id="granadepowerup" path="PowerUps/granadePowerUp"/>
    <texture id="void" path="Effects/void" />
    <texture id="plasmagranade" path="Weapons/plasmagranade"/>
    <texture id="scope" path="Weapons/scope"/>
    <texture id="blood" path="Effects/blood"/>
  </texturesDeclaration>

  <randomVariablesDeclaration>
    <randomVariable id="asteroidLife" mean="20" meanIncrementPerMinute="2" standardDeviation="10" minValue="5" maxValue="100" />
    <randomVariable id="asteroidSpeed" mean="100" meanIncrementPerMinute="20" standardDeviation="50" minValue="10" maxValue="1000" />
    <randomVariable id="enemyEasyLife" mean="5" meanIncrementPerMinute="1" standardDeviation="5" minValue="1" maxValue="30" />
    <randomVariable id="enemyEasySpeed" mean="1" meanIncrementPerMinute="0.1" standardDeviation="0.2" minValue="0.01" maxValue="0.5" />
    <randomVariable id="enemyNormalLife" mean="7" meanIncrementPerMinute="1" standardDeviation="7" minValue="1" maxValue="40" />
    <randomVariable id="enemyNormalSpeed" mean="1.3" meanIncrementPerMinute="0.1" standardDeviation="0.4" minValue="0.01" maxValue="0.6" />
    <randomVariable id="tachyonStreamDuration" mean="5" maxValue="7" minValue="3" standardDeviation="3" />
  </randomVariablesDeclaration>

  <startlevel>
    <backgroundTexture timestamp="0" texture="stars" level="0" speed="200"/>
    <backgroundTexture timestamp="0" texture="stars" level="1" speed="221"/>
    <asteroidRandomizer timestamp="5" texture="asteroid" launchProbabilityPerSecond="0.08" probabilityIncrementPerMinute="0.05" 
                        pobabilityMax="0.2" lifeRandomVariable="asteroidLife" speedRandomVariable="asteroidSpeed" />
    <enemyRandomizer timestamp="5" texture="enemyeasy" launchProbabilityPerSecond="0.1" probabilityIncrementPerMinute="0.1"
                     powerUpProbabilityPerLaunch="0.25" granadePowerUpProbability="0.2" rocketPowerUpProbability="0.3" weapon="Gun"
                     lifeRandomVariable="enemyEasyLife" speedRandomVariable="enemyEasySpeed" />
    <enemyRandomizer timestamp="5" texture="enemynormal" launchProbabilityPerSecond="0.06" probabilityIncrementPerMinute="0.1"
                     powerUpProbabilityPerLaunch="0.35" granadePowerUpProbability="0.3" rocketPowerUpProbability="0.4" weapon="RocketLauncher"
                     lifeRandomVariable="enemyNormalLife" speedRandomVariable="enemyNormalSpeed" pobabilityMax="0.8"/>
    <tachyonStreamRandomizer timestamp="20" texture="tachyonstream" launchProbabilityPerSecond="0.1" durationRandomVariable="tachyonStreamDuration"/>
  </startlevel>
  <endlevel />
</level>
